version: '3.8'
services:
  productos:
    build: ./FoodExpres-Productos
    ports:
      - "8001:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  clientes:
    build: ./FoodExpress-Clientes
    ports:
      - "8002:8002"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  cocina_menu:
    build: ./FoodExpress-Cocina_Menu
    ports:
      - "8003:8003"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  comentarios:
    build: ./FoodExpress-Comentarios
    ports:
      - "8004:8004"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  pedidos:
    build: ./FoodExpress-Pedidos
    ports:
      - "8005:8005"
    environment:
      - SPRING_PROFILES_ACTIVE=prod